### ISSUE TITLE
Need to set windowing modules

### ISSUE THREAD

**Issue by brambozz** [mreppen/kakoune-sway#1]
I tried to use your plugin today, and initially tried with the config as suggested in the README, i.e.:
```
plug 'mreppen/kakoune-sway' %{
  # Suggested mapping
  map global user 3 ': enter-user-mode sway<ret>' -docstring 'Sway…'
}
```
This gave me the error `termcmd not set` when trying to use any of the commands. When adding the line suggested in kakoune-i3's [README](https://github.com/Delapouite/kakoune-i3#install), the plugin works, i.e.:
```
set-option global windowing_modules 'x11'
```
Is this the expected behaviour? Anyway, sweet plugin!

**Comment by mreppen** [comment]
It appears github doesn't automatically add activity notification watching to one's own repositories.  I wish I had seen this sooner.

On my side it works, but I assume it is loaded with something else already.  I recall reading about this change last fall, but didn't think of it at the time.  Thanks for catching it.

Fixed in e20879b
